In [10]:
# ### Q1. Create a Pandas Series from a list of integers.
# > 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

numbers = [10, 20, 30, 40, 50]

a = pd.Series(numbers)
print(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [13]:
### Q2. Create a Series from a dictionary with custom index.

dict = {
    "math": 95,
    "science": 90,
    "english": 85
}

S = pd.Series(dict)
print(S)

math       95
science    90
english    85
dtype: int64

In [2]:
### Q3. Access elements using index labels.

import pandas as pd

s = pd.Series(
    [85, 90, 78, 92],index=["a", "b", "c", "d"]
)

# Single value
print(s["a"])

# Multiple values
print(s[["a", "b"]])

# Range of labels (inclusive)
print(s["a":"c"])

85
a    85
b    90
dtype: int64
a    85
b    90
c    78
dtype: int64

In [4]:
### Q4. Perform arithmetic operations on a Series.

s = pd.Series([10, 20, 30, 40, 50])

print(s + 5)    # Addition
print(s - 5)    # Subtraction
print(s * 2)    # Multiplication
print(s / 2)    # Division
print(s // 3)   # Floor division
print(s % 3)    # Modulus
print(s ** 2)   # Power

0    15
1    25
2    35
3    45
4    55
dtype: int64
0     5
1    15
2    25
3    35
4    45
dtype: int64
0     20
1     40
2     60
3     80
4    100
dtype: int64
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0
dtype: float64
0     3
1     6
2    10
3    13
4    16
dtype: int64
0    1
1    2
2    0
3    1
4    2
dtype: int64
0     100
1     400
2     900
3    1600
4    2500
dtype: int64

In [6]:
### Q5. Find mean, min, max of a Series.

s = pd.Series([10, 20, 30, 40, 50])

print("Mean:", s.mean())
print("Min :", s.min())
print("Max :", s.max())

Mean: 30.0
Min : 10
Max : 50

In [8]:
# ### Q6. Apply conditional filtering on a Series.
# >**Hint:** Use a boolean mask: `s[s > 50]`. You can also chain condition  s with `&` and `|`.

import pandas as pd

s = pd.Series([25, 60, 45, 80, 55, 30])

# Values greater than 50
print(s[s > 50])


# Values between 40 and 70
print(s[(s > 40) & (s < 70)])

# Values less than 30 OR greater than 70
print(s[(s < 30) | (s > 70)])

1    60
3    80
4    55
dtype: int64
1    60
2    45
4    55
dtype: int64
0    25
3    80
dtype: int64

In [9]:
### Q7. Replace values in a Series.

s = pd.Series([10, 20, 30, 20, 40])

# Replace a single value
print(s.replace(20, 99))

# Replace a multiple value
print(s.replace({10: 100, 20: 200, 40: 400}))

0    10
1    99
2    30
3    99
4    40
dtype: int64
0    100
1    200
2     30
3    200
4    400
dtype: int64

In [11]:
import pandas as pd

s = pd.Series(["IT", "HR", "IT", "Finance"])

print(s.replace("IT", "comp"))

0       comp
1         HR
2       comp
3    Finance
dtype: object

In [ ]:
### Q8. Convert Series data type.
import pandas as pd

s = pd.Series(["10", "20", "30", "40"])

# Convert string Series to integer
s_int = s.astype(int)

print(s_int)
print(s_int.dtype)

0    10
1    20
2    30
3    40
dtype: int64
int64

In [16]:
# Convert to Float
s_float = s.astype(float)

print(s_float)
print(s_float.dtype)

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float64
float64

In [19]:
# Convert to Category

s = pd.Series(["IT", "HR", "IT", "Finance"])

s_cat = s.astype("category")

print(s_cat)
print(s_cat.dtype)

0         IT
1         HR
2         IT
3    Finance
dtype: category
Categories (3, object): ['Finance', 'HR', 'IT']
category

In [22]:
### Q9. Check for null values in Series.

import pandas as pd
import numpy as np

s = pd.Series([10, np.nan, 30, None, 50])

# Check null values
print(s.isnull())

# Count Null Values
print(s.isnull().sum())

0    False
1     True
2    False
3     True
4    False
dtype: bool
2

In [23]:
print(s.notnull())

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [27]:
### Q10. Fill missing values in Series.

s = pd.Series([10, np.nan, 30, np.nan, 50])

# Fill missing values with a constant
print(s.fillna(0))

0    10.0
1     0.0
2    30.0
3     0.0
4    50.0
dtype: float64

In [ ]:
# Fill with Mean
print(s.fillna(s.mean()))

0    10.0
1    30.0
2    30.0
3    30.0
4    50.0
dtype: float64

In [26]:
# Forward Fill (ffill)
print(s.ffill())

0    10.0
1    10.0
2    30.0
3    30.0
4    50.0
dtype: float64

In [29]:
# Backward Fill (bfill)
print(s.bfill())

0    10.0
1    30.0
2    30.0
3    50.0
4    50.0
dtype: float64

In [30]:

### Q11. Create DataFrame from a list.

import pandas as pd

data = [
    ["Jay", 25, "IT"],
    ["Manoj", 30, "HR"],
    ["Anand", 28, "Finance"]
]

df = pd.DataFrame(data, columns=["Name", "Age", "Department"])

print(df)

    Name  Age Department
0    Jay   25         IT
1  Manoj   30         HR
2  Anand   28    Finance

In [35]:
### Q12. Create DataFrame from a dictionary.
# **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

import pandas as pd

data = {
    "Name": ["ajay", "salman", "ketan"],
    "Age": [25, 30, 28],
    "Department": ["IT", "HR", "Finance"]
}

df = pd.DataFrame(data)

print(df)

     Name  Age Department
0    ajay   25         IT
1  salman   30         HR
2   ketan   28    Finance

In [36]:

# ### Q13. Create DataFrame from list of dictionaries.
# > 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

data = [
    {"Name": "John", "Age": 25, "Department": "IT"},
    {"Name": "Mary", "Age": 30, "Department": "HR"},
    {"Name": "Alice", "Age": 28}
]

df = pd.DataFrame(data)

print(df)

    Name  Age Department
0   John   25         IT
1   Mary   30         HR
2  Alice   28        NaN

In [37]:
# ### Q14. Display DataFrame structure (shape, columns, dtypes).
# > 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice"],
    "Age": [25, 30, 28],
    "Department": ["IT", "HR", "Finance"]
})

# Shape of DataFrame (rows, columns)
print("Shape:", df.shape)

# Column names
print("Columns:", df.columns)

# Data types of each column
print("\nDtypes:\n", df.dtypes)

# Summary info
print("\nInfo:")
df.info()

# Statistical summary (only numeric columns)
print("\nDescribe:\n", df.describe())

Shape: (3, 3)
Columns: Index(['Name', 'Age', 'Department'], dtype='object')

Dtypes:
 Name          object
Age            int64
Department    object
dtype: object

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      object
 1   Age         3 non-null      int64
 2   Department  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

Describe:
              Age
count   3.000000
mean   27.666667
std     2.516611
min    25.000000
25%    26.500000
50%    28.000000
75%    29.000000
max    30.000000

In [3]:
# ### Q15. Select single column from DataFrame.
# > 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice"],
    "Age": [25, 30, 28],
    "Department": ["IT", "HR", "Finance"]
})

# Select single column using bracket notation
print(df["Name"])

# Dot Notation
print(df.Name)

0     John
1     Mary
2    Alice
Name: Name, dtype: object
0     John
1     Mary
2    Alice
Name: Name, dtype: object

In [5]:
# ### Q16. Select multiple columns.
# **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.


# Select single column using bracket notation
print(df[["Name","Age"]])

    Name  Age
0   John   25
1   Mary   30
2  Alice   28

In [24]:
# ### Q17. Add new column with scalar value.
# > 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice"],
    "Age": [25, 30, 28]
})

# Add new column with a scalar value
df["salary"] = 100

print(df)

    Name  Age  salary
0   John   25     100
1   Mary   30     100
2  Alice   28     100

In [21]:
# ### Q18. Add column using Series.
#**Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

df["Bonus"] = pd.Series([25, 30, 28])
print(df)

    Name  Age  salary  Bonus
0   John   25     100     25
1   Mary   30     100     30
2  Alice   28     100     28

In [25]:
# ### Q19. Rename columns using `rename()`.
# > 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

df.rename(columns={"Name": "Employee_Name"}, inplace=True)

print(df)

  Employee_Name  Age  salary
0          John   25     100
1          Mary   30     100
2         Alice   28     100

In [28]:
# ### Q20. Rename multiple columns.
# > 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

df.rename(
    columns={
        "Name": "Employee_Name",
        "Age": "Employee_Age",
       
    },
    inplace=True
)

print(df)

  Employee_Name  Employee_Age  salary
0          John            25     100
1          Mary            30     100
2         Alice            28     100

In [24]:
# ### Q21. Select rows using `loc`.
# > 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice", "Bob", "jack"],
    "Age": [25, 30, 28, 22, 25],
    "City": ["New York", "London", "Paris", "Tokyo","canada"],
    "Salary": [50000, 60000, 55000, 65000,70000],
    "Department": ["IT", "HR", "IT","comp","mech"],

}, index=["E1", "E2", "E3", "E4","E5"])

print(df)

     Name  Age      City  Salary Department
E1   John   25  New York   50000         IT
E2   Mary   30    London   60000         HR
E3  Alice   28     Paris   55000         IT
E4    Bob   22     Tokyo   65000       comp
E5   jack   25    canada   70000       mech

In [25]:
df.loc["E2"]

Name            Mary
Age               30
City          London
Salary         60000
Department        HR
Name: E2, dtype: object

In [26]:
#  Select multiple rows
df.loc[["E1", "E3"]]

     Name  Age      City  Salary Department
E1   John   25  New York   50000         IT
E3  Alice   28     Paris   55000         IT

In [27]:
# Select a range of rows (IMPORTANT)

df.loc["E1":"E3"]              # ✔ loc range is inclusive on both ends
                               # So "E3" is included.

     Name  Age      City  Salary Department
E1   John   25  New York   50000         IT
E2   Mary   30    London   60000         HR
E3  Alice   28     Paris   55000         IT

In [28]:
# ### Q22. Select rows using `iloc`.
# > 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

df.iloc[0]

Name              John
Age                 25
City          New York
Salary           50000
Department          IT
Name: E1, dtype: object

In [ ]:
df.iloc[[0, 2]]            #0 = E1 / 2 = E3

     Name  Age      City  Salary Department
E1   John   25  New York   50000         IT
E3  Alice   28     Paris   55000         IT

In [31]:
df.iloc[1:4]          # End index is NOT included

     Name  Age    City  Salary Department
E2   Mary   30  London   60000         HR
E3  Alice   28   Paris   55000         IT
E4    Bob   22   Tokyo   65000       comp

In [32]:
# ### Q23. Access specific row and column.
# > 💡 **Hint:** `df.loc[row_label, "col_name"]` or 
# `df.iloc[row_pos, col_pos]` for a single cell.

# df.loc[row_label, "col_name"]
df.loc["E2", "Name"]

'Mary'

In [33]:
# `df.iloc[row_pos, col_pos]` for a single cell.

df.iloc[1, 2]

'London'

In [34]:
# ### Q24. Select subset using multiple rows & columns.
# > 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

print(df.loc[["E1","E2"], ["Name","Age"]])

    Name  Age
E1  John   25
E2  Mary   30

In [35]:
print(df.iloc[[0,1], [0,2]])         # 0= Name / 2 = city

    Name      City
E1  John  New York
E2  Mary    London

In [36]:
# ### Q25. Apply conditional filtering using `loc`.
# > 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

print(df.loc[df["Age"] > 25, ["Name","City"]])

     Name    City
E2   Mary  London
E3  Alice   Paris

In [37]:
# ### Q26. Slice rows using index range.
# > 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or 
# `df.loc[label1:label2]` for label-based slicing.


# df.iloc[start:end]
print(df.iloc[0:2])              # Start = 0 (included) End = 2 (excluded)

    Name  Age      City  Salary Department
E1  John   25  New York   50000         IT
E2  Mary   30    London   60000         HR

In [38]:
# df.loc[label1:label2]
print(df.loc["E1":"E3"])             # loc includes both start and end labels.

     Name  Age      City  Salary Department
E1   John   25  New York   50000         IT
E2   Mary   30    London   60000         HR
E3  Alice   28     Paris   55000         IT

In [39]:
# ### Q27. Slice columns using labels.
# > 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).


print(df.loc[:, "Name":"City"])             # columns from Name to City

     Name  Age      City
E1   John   25  New York
E2   Mary   30    London
E3  Alice   28     Paris
E4    Bob   22     Tokyo
E5   jack   25    canada

In [ ]:

# ### Q28. Slice columns using position.
# > 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

print(df.iloc[:, 1:4])                # end[4] - not included

    Age      City  Salary
E1   25  New York   50000
E2   30    London   60000
E3   28     Paris   55000
E4   22     Tokyo   65000
E5   25    canada   70000

In [ ]:
# ### Q29. Perform combined row & column slicing.
# > 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

#df.loc[row_condition, ["col1","col2"]]
df.loc[df["Department"] == "IT", ["Name", "Salary"]]

     Name  Salary
E1   John   50000
E3  Alice   55000

In [49]:
# df.iloc[0:5, [0, 2, 4]]
df.iloc[0:5, [0, 2, 4]]

     Name      City Department
E1   John  New York         IT
E2   Mary    London         HR
E3  Alice     Paris         IT
E4    Bob     Tokyo       comp
E5   jack    canada       mech

In [ ]:
# ### Q30. Set a column as index.
# > 💡 **Hint:** Use `df.set_index("col_name")`.
# Add `inplace=True` to modify without reassigning.

df = pd.DataFrame({
    "EmployeeID": ["E1", "E2", "E3"],
    "Name": ["John", "Mary", "Alice"],
    "Salary": [50000, 60000, 55000]
})

df.set_index("EmployeeID", inplace=True)

print(df)

             Name  Salary
EmployeeID
E1           John   50000
E2           Mary   60000
E3          Alice   55000

In [125]:
# ### Q31. Create hierarchical index (MultiIndex).
# > 💡 **Hint:** `df.set_index(["col1","col2"])` —
# pass a **list** of column names to create a MultiIndex.


import pandas as pd

df = pd.DataFrame({
    "EmployeeID": ["E1", "E2", "E3", "E4"],
    "Department": ["IT", "HR", "IT", "Finance"],
    "Name": ["John", "Mary", "Alice", "Bob"],
    "Salary": [50000, 60000, 55000, 70000]
})

print(df)

  EmployeeID Department   Name  Salary
0         E1         IT   John   50000
1         E2         HR   Mary   60000
2         E3         IT  Alice   55000
3         E4    Finance    Bob   70000

In [126]:
# Create MultiIndex
df.set_index(["Department", "EmployeeID"], inplace=True)

print(df)

                        Name  Salary
Department EmployeeID
IT         E1           John   50000
HR         E2           Mary   60000
IT         E3          Alice   55000
Finance    E4            Bob   70000

In [127]:
# ### Q32. Reset index.
# > 💡 **Hint:** `df.reset_index()` — moves the current index back to a column.
# Use `inplace=True` to modify in-place.

df.reset_index(inplace=True)
print(df)

  Department EmployeeID   Name  Salary
0         IT         E1   John   50000
1         HR         E2   Mary   60000
2         IT         E3  Alice   55000
3    Finance         E4    Bob   70000

In [128]:
# ### Q33. Reset multi-index.
# > 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame 
# flattens both index levels back to columns.

df.reset_index()
print(df)

  Department EmployeeID   Name  Salary
0         IT         E1   John   50000
1         HR         E2   Mary   60000
2         IT         E3  Alice   55000
3    Finance         E4    Bob   70000

In [134]:

# ### Q34. Convert index to column.
# > 💡 **Hint:** `df.reset_index()` by default moves the index to a column.
# Use `drop=False` (default) to keep it.

df.reset_index(drop=False)
print(df)

  Department EmployeeID   Name  Salary
0         IT         E1   John   50000
1         HR         E2   Mary   60000
2         IT         E3  Alice   55000
3    Finance         E4    Bob   70000

In [141]:
# ### Q35. Use drop option in `reset_index`.
# > 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely
# instead of converting it to a column.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice"],
    "Salary": [50000, 60000, 55000]
}, index=["E1", "E2", "E3"])

print(df)

     Name  Salary
E1   John   50000
E2   Mary   60000
E3  Alice   55000

In [142]:
df.reset_index()    # # index reset into column

  index   Name  Salary
0    E1   John   50000
1    E2   Mary   60000
2    E3  Alice   55000

In [ ]:
# 👉 removes old index
# 👉 creates fresh numeric index (0,1,2...)

df.reset_index(drop=True)

    Name  Salary
0   John   50000
1   Mary   60000
2  Alice   55000

In [ ]:
# ### Q36. Perform label-based indexing.
# > 💡 **Hint:** Use `df.loc[label]`
# — works with any index type (string, integer, datetime labels).


# 1. Select a single row using label
df.loc["E2"]

Name       Mary
Salary    60000
Name: E2, dtype: object

In [147]:
# ### Q37. Perform position-based indexing.
# > 💡 **Hint:** Use `df.iloc[0]` — always integer-based, 
# regardless of the index type.

df.iloc[0]

Name       John
Salary    50000
Name: E1, dtype: object

In [153]:
# ### Q38. Access first N rows.
# > 💡 **Hint:** `df.head(N)` — default N is 5.

# Default behavior (first 5 rows)
df.head(1)

    Name  Salary
E1  John   50000

In [152]:
# ### Q39. Access last N rows.
# > 💡 **Hint:** `df.tail(N)` — default N is 5.

df.tail(1)

     Name  Salary
E3  Alice   55000

In [155]:
# ### Q40. Extract random sample from DataFrame.
# > 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` 
# for 20% of rows. Set `random_state` for reproducibility.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice", "Bob", "Tom", "Emma"],
    "Age": [25, 30, 28, 22, 35, 27],
    "Salary": [50000, 60000, 55000, 65000, 70000, 52000]
})

print(df)

    Name  Age  Salary
0   John   25   50000
1   Mary   30   60000
2  Alice   28   55000
3    Bob   22   65000
4    Tom   35   70000
5   Emma   27   52000

In [156]:
# 1. Random N rows
df.sample(n=3)

    Name  Age  Salary
2  Alice   28   55000
5   Emma   27   52000
1   Mary   30   60000

In [159]:
#  2. Random fraction of rows
df.sample(frac=0.5)

    Name  Age  Salary
5   Emma   27   52000
0   John   25   50000
2  Alice   28   55000

In [ ]:
# 3. Reproducible randomness (random_state)
df.sample(n=3, random_state=42)       # 42- It is just a popular convention

   Name  Age  Salary
0  John   25   50000
1  Mary   30   60000
5  Emma   27   52000

In [180]:
# ### Q41. Detect missing values using `isnull()`.
# > 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()`
# for column-wise counts or `.isnull().any()` to check if any exist.

import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["John", "Mary", None],
    "Age": [25, None, 30],
    "Salary": [50000, 60000, 70000]
})

print(df.isnull())

    Name    Age  Salary
0  False  False   False
1  False   True   False
2   True  False   False

In [181]:
#  2. Count missing values (very important)
df.isnull().sum()

Name      1
Age       1
Salary    0
dtype: int64

In [182]:
# 3. Check if ANY missing values exist
print(df.isnull().any())

Name       True
Age        True
Salary    False
dtype: bool

In [183]:
#  4. Check if DataFrame has ANY missing value
print(df.isnull().values.any())        # 👉 Entire dataset has missing values or not

True

In [184]:
# ### Q42. Drop missing values using `dropna()`.
# > 💡 **Hint:** `df.dropna()` drops any row with a NaN. 
# Use `axis=1` for columns, `subset=["col"]` for specific columns, 
# and `thresh=N` to keep rows with at least N non-null values.

# 1. Drop rows with ANY missing value (default)
df.dropna()

   Name   Age  Salary
0  John  25.0   50000

In [185]:
# 2. Drop columns with missing values
df.dropna(axis=1)

   Salary
0   50000
1   60000
2   70000

In [186]:
# 3. Drop based on specific column (subset)
df.dropna(subset=["Age"])

   Name   Age  Salary
0  John  25.0   50000
2  None  30.0   70000

In [ ]:
#  4. Keep rows with minimum non-null values (thresh)
df.dropna(thresh=2)      # thresh=N  => Keep rows with at least 2 non-NaN values

   Name   Age  Salary
0  John  25.0   50000
1  Mary   NaN   60000
2  None  30.0   70000

In [188]:
# ### Q43. Fill missing values with a constant.
# > 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`.
# You can also pass a dict to fill different columns with different values.

# 1. Fill ALL missing values with a constant
df.fillna(0)

   Name   Age  Salary
0  John  25.0   50000
1  Mary   0.0   60000
2     0  30.0   70000

In [189]:
# 2. Fill a specific column
df["Name"].fillna("Unknown")

0       John
1       Mary
2    Unknown
Name: Name, dtype: object

In [190]:
# 3. Fill different values for different columns (VERY IMPORTANT)

df.fillna({
    "Name": "Unknown",
    "Age": 0,
    "City": "Not Available"
})

      Name   Age  Salary
0     John  25.0   50000
1     Mary   0.0   60000
2  Unknown  30.0   70000

In [197]:
# 4. Modify original DataFrame
df.fillna(0, inplace=False)                # Changes df permanently

   Name   Age  Salary
0  John  25.0   50000
1  Mary   0.0   60000
2     0  30.0   70000

In [200]:
# ### Q44. Fill missing values using mean/median.
# > 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or
# `df["col"].fillna(df["col"].median())`.

import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [25, None, 30, 28, None],
    "Salary": [50000, 60000, None, 55000, 70000]
})

print(df)

    Age   Salary
0  25.0  50000.0
1   NaN  60000.0
2  30.0      NaN
3  28.0  55000.0
4   NaN  70000.0

In [ ]:
# mean
df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df)

         Age   Salary
0  25.000000  50000.0
1  27.666667  60000.0
2  30.000000      NaN
3  28.000000  55000.0
4  27.666667  70000.0

In [202]:
# median
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
print(df)

         Age   Salary
0  25.000000  50000.0
1  27.666667  60000.0
2  30.000000  57500.0
3  28.000000  55000.0
4  27.666667  70000.0

In [204]:
# ### Q45. Use forward fill and backward fill.
# > 💡 **Hint:** `df.ffill()` propagates the last valid value forward. 
# `df.bfill()` fills using the next valid value.

import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Value": [10, None, None, 40, None]
})

print(df)

   Value
0   10.0
1    NaN
2    NaN
3   40.0
4    NaN

In [205]:
df.ffill()

   Value
0   10.0
1   10.0
2   10.0
3   40.0
4   40.0

In [206]:
df.bfill()

   Value
0   10.0
1   40.0
2   40.0
3   40.0
4    NaN

In [208]:
# ### Q46. Convert data type using `astype()`.
# > 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`.
# Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

import pandas as pd

df = pd.DataFrame({
    "Age": ["25", "30", "28"],
    "Salary": ["50000", "60000", "55000"],
    "Score": [90.5, 88.2, 91.0]
})

print(df)

  Age Salary  Score
0  25  50000   90.5
1  30  60000   88.2
2  28  55000   91.0

In [211]:
# 1. Convert string → integer

df["Age"] = df["Age"].astype(int)
df["Salary"] = df["Salary"].astype(int)

print(df)

   Age  Salary  Score
0   25   50000   90.5
1   30   60000   88.2
2   28   55000   91.0

In [214]:
#  2. Convert to float
df["Age"] = df["Age"].astype(float) 
print(df)

print(type(df))

    Age  Salary  Score
0  25.0   50000   90.5
1  30.0   60000   88.2
2  28.0   55000   91.0
<class 'pandas.core.frame.DataFrame'>

In [216]:
#  3. Convert to category (memory optimization)
df["Age"] = df["Age"].astype("category")

print(df)

    Age  Salary  Score
0  25.0   50000   90.5
1  30.0   60000   88.2
2  28.0   55000   91.0

In [219]:
# 4. Handling invalid values (IMPORTANT)

df = pd.DataFrame({
    "Age": ["25", "30", "abc", "28"]
})

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

print(df)

    Age
0  25.0
1  30.0
2   NaN
3  28.0

In [220]:
# ### Q47. Clean string column using `.str.lower()`.
# > 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`.
# Similarly `.str.upper()`, `.str.title()`.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "MARY", "aLiCe", "Bob"],
    "City": ["New York", "LONDON", "paris", "TOKYO"]
})

print(df)

    Name      City
0   John  New York
1   MARY    LONDON
2  aLiCe     paris
3    Bob     TOKYO

In [222]:
#  1. Convert to lowercase
df["Name"] = df["Name"].str.lower()
df["City"] = df["City"].str.lower()

print(df)

    Name      City
0   john  new york
1   mary    london
2  alice     paris
3    bob     tokyo

In [224]:
# 2. Convert to uppercase
df["Name"] = df["Name"].str.upper()

print(df)

    Name      City
0   JOHN  new york
1   MARY    london
2  ALICE     paris
3    BOB     tokyo

In [225]:
# 3. Convert to title case (first letter capital)
df["City"] = df["City"].str.title()

print(df)

    Name      City
0   JOHN  New York
1   MARY    London
2  ALICE     Paris
3    BOB     Tokyo

In [226]:
# ## Q48. Trim whitespace in strings.
# > 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces.
# Use `.str.lstrip()` / `.str.rstrip()` for one side.

import pandas as pd

df = pd.DataFrame({
    "Name": [" John ", "Mary  ", "  Alice", "Bob"],
    "City": [" New York ", "London ", " Paris", "Tokyo  "]
})

print(df)

      Name        City
0    John    New York
1   Mary       London
2    Alice       Paris
3      Bob     Tokyo

In [228]:
# 1. Remove BOTH sides spaces (strip)
df["Name"] = df["Name"].str.strip()
df["City"] = df["City"].str.strip()

print(df)

    Name      City
0   John  New York
1   Mary    London
2  Alice     Paris
3    Bob     Tokyo

In [229]:
# 2. Remove ONLY left spaces (lstrip)
df["Name"] = df["Name"].str.lstrip()

In [ ]:
#  3. Remove ONLY right spaces (rstrip)
df["City"] = df["City"].str.rstrip()

In [230]:
# ### Q49. Replace substring in column.
# > 💡 **Hint:** `df["col"].str.replace("old", "new")`.
# Add `regex=True` for pattern-based replacement.

import pandas as pd

df = pd.DataFrame({
    "Email": ["john@gmail.com", "mary@gmail.com", "alice@yahoo.com", "bob@gmail.com"]
})

print(df)

             Email
0   john@gmail.com
1   mary@gmail.com
2  alice@yahoo.com
3    bob@gmail.com

In [ ]:
# # 1. Replace simple substring

# Replace "gmail.com" with "company.com"

df["Email"] = df["Email"].str.replace("gmail.com", "company.com")

print(df)

              Email
0  john@company.com
1  mary@company.com
2   alice@yahoo.com
3   bob@company.com

In [ ]:
# 2. Replace using pattern (regex)
# If you want to replace all domains, use regex:
# @.* - everything after @
# Python raw strings (r"")
df["Email"] = df["Email"].str.replace(r"@.*", "@company.com", regex=True)

print(df)

               Email
0   john@company.com
1   mary@company.com
2  alice@company.com
3    bob@company.com

In [236]:
# ### Q50. Extract part of string using `.str`.
# > 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. 
# Use `.str.split("@").str[1]` to extract after a delimiter.

import pandas as pd

df = pd.DataFrame({
    "Name": ["Johnathan", "Maryam", "Alice", "Bob"],
    "Email": ["john@gmail.com", "mary@yahoo.com", "alice@outlook.com", "bob@gmail.com"]
})

print(df)

        Name              Email
0  Johnathan     john@gmail.com
1     Maryam     mary@yahoo.com
2      Alice  alice@outlook.com
3        Bob      bob@gmail.com

In [239]:
#  1. Extract first N characters
df["ShortName"] = df["Name"].str[:3]
print(df)

        Name              Email ShortName
0  Johnathan     john@gmail.com       Joh
1     Maryam     mary@yahoo.com       Mar
2      Alice  alice@outlook.com       Ali
3        Bob      bob@gmail.com       Bob

In [240]:
# 2. Extract part after a delimiter (very important)

df["Domain"] = df["Email"].str.split("@").str[1]

print(df)

        Name              Email ShortName       Domain
0  Johnathan     john@gmail.com       Joh    gmail.com
1     Maryam     mary@yahoo.com       Mar    yahoo.com
2      Alice  alice@outlook.com       Ali  outlook.com
3        Bob      bob@gmail.com       Bob    gmail.com

In [241]:
# 3. Extract username (before @)
df["User"] = df["Email"].str.split("@").str[0] 
print(df)

        Name              Email ShortName       Domain   User
0  Johnathan     john@gmail.com       Joh    gmail.com   john
1     Maryam     mary@yahoo.com       Mar    yahoo.com   mary
2      Alice  alice@outlook.com       Ali  outlook.com  alice
3        Bob      bob@gmail.com       Bob    gmail.com    bob

In [1]:
# ### Q51. Detect duplicate rows.
# > 💡 **Hint:** `df.duplicated()` returns a boolean Series. 
# Use `df[df.duplicated()]` to see the actual duplicate rows.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "John", "Alice"],
    "Age": [25, 30, 25, 28]
})

print(df.duplicated())

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
# ### Q52. Remove duplicates using `drop_duplicates()`.
# > 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. 
# Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

# Default behavior (keep="first")
print(df.drop_duplicates())          # default - df.drop_duplicates(keep="first")

    Name  Age
0   John   25
1   Mary   30
3  Alice   28

In [ ]:
# Keep the last occurrence
df.drop_duplicates(keep="last")         # first "John, 25" row is removed

    Name  Age
1   Mary   30
2   John   25
3  Alice   28

In [4]:
# Remove all duplicates
df.drop_duplicates(keep=False)

    Name  Age
1   Mary   30
3  Alice   28

In [ ]:
# Check duplicates using specific columns
df.drop_duplicates(subset=["Name"])        


# df.drop_duplicates(inplace=True) =  Modify original DataFrame

    Name  Age
0   John   25
1   Mary   30
3  Alice   28

In [7]:
# ### Q53. Rename row labels.
# > 💡 **Hint:** `df.rename(index={old_label: new_label})`.

import pandas as pd

df = pd.DataFrame(
    {
        "Name": ["John", "Mary", "Alice"],
        "Age": [25, 30, 28]
    },
    index=["E1", "E2", "E3"]
)

print(df)

     Name  Age
E1   John   25
E2   Mary   30
E3  Alice   28

In [8]:
# Rename a single row label

df = df.rename(index={"E1": "EMP1"})
print(df)

       Name  Age
EMP1   John   25
E2     Mary   30
E3    Alice   28

In [9]:
# Rename multiple row labels

df = df.rename(index={
    "E2": "EMP2",
    "E3": "EMP3"
})

print(df)

       Name  Age
EMP1   John   25
EMP2   Mary   30
EMP3  Alice   28

In [10]:
# Rename all row labels at once
df.index = ["A", "B", "C"]

print(df)

    Name  Age
A   John   25
B   Mary   30
C  Alice   28

In [11]:
# ### Q54. Handle inconsistent data.
# > 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. 
# Use `.replace({...})` to map inconsistent values to a standard form.

import pandas as pd

df = pd.DataFrame({
    "Gender": ["Male", " male ", "MALE", "Female", "F", "female"],
    "City": [" Mumbai ", "mumbai", "MUMBAI", "Delhi", " delhi ", "DELHI"]
})

print(df)

   Gender      City
0    Male   Mumbai
1   male     mumbai
2    MALE    MUMBAI
3  Female     Delhi
4       F    delhi
5  female     DELHI

In [ ]:
#  Remove Extra Spaces
df["Gender"] = df["Gender"].str.strip()
df["City"] = df["City"].str.strip()

print(df)

   Gender    City
0    Male  Mumbai
1    male  mumbai
2    MALE  MUMBAI
3  Female   Delhi
4       F   delhi
5  female   DELHI

In [15]:
# Convert to Lowercase
df["Gender"] = df["Gender"].str.lower()
df["City"] = df["City"].str.lower()

print(df)

   Gender    City
0    male  mumbai
1    male  mumbai
2    male  mumbai
3  female   delhi
4       f   delhi
5  female   delhi

In [20]:
#  Standardize Values Using .replace()
df["Gender"] = df["Gender"].replace({
    "m": "male",
    "f": "female"
})

print(df)

   Gender    City
0    male  mumbai
1    male  mumbai
2    male  mumbai
3  female   delhi
4  female   delhi
5  female   delhi

In [22]:
# ### Q55. Replace values in DataFrame.
# > 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. 
# Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

 
# Replace a Single Value
df = df.replace("mumbai", "Pune")

print(df)

   Gender   City
0    male   Pune
1    male   Pune
2    male   Pune
3  female  delhi
4  female  delhi
5  female  delhi

In [23]:
#  Replace Multiple Values Using a Dictionary

df = df.replace({
    "Pune": "Mumbai",
    "delhi": "New Delhi"
})

print(df)

   Gender       City
0    male     Mumbai
1    male     Mumbai
2    male     Mumbai
3  female  New Delhi
4  female  New Delhi
5  female  New Delhi

In [25]:
# ### Q56. Detect outliers in a column.
# > 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1.
# Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. 
# Alternatively use Z-score: `|z| > 3`.

import pandas as pd

df = pd.DataFrame({
    "Salary": [30000, 35000, 40000, 45000, 50000, 200000]
})

print(df)

   Salary
0   30000
1   35000
2   40000
3   45000
4   50000
5  200000

In [26]:
#  Calculate Q1, Q3, and IQR
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)

Q1 = 36250.0
Q3 = 48750.0
IQR = 12500.0

In [27]:
# Calculate Bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(lower_bound)
print(upper_bound)

17500.0
67500.0

In [28]:
# Detect Outliers
outliers = df[
    (df["Salary"] < lower_bound) |
    (df["Salary"] > upper_bound)
]

print(outliers)

   Salary
5  200000

In [31]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

outliers = df[
    (df["Salary"] < Q1 - 1.5 * IQR) |
    (df["Salary"] > Q3 + 1.5 * IQR)
]

print(outliers)

   Salary
5  200000

In [32]:
# ### Q57. Handle outliers using clipping.
# > 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values
# outside the bounds with the boundary values.

import pandas as pd

df = pd.DataFrame({
    "Salary": [30000, 35000, 40000, 45000, 50000, 200000]
})

Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df["Salary"] = df["Salary"].clip(
    lower=lower_bound,
    upper=upper_bound
)

print(df)

   Salary
0   30000
1   35000
2   40000
3   45000
4   50000
5   67500

In [33]:

# ### Q58. Standardize column names.
# > 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")`
# — clean all column names in one line.

import pandas as pd

df = pd.DataFrame({
    " First Name ": ["John", "Mary"],
    "LAST NAME": ["Doe", "Smith"],
    "Age ": [25, 30]
})

print(df.columns)

Index([' First Name ', 'LAST NAME', 'Age '], dtype='object')

In [34]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print(df.columns)

Index(['first_name', 'last_name', 'age'], dtype='object')

In [35]:
# ### Q59. Handle mixed data types in a column.
# > 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers,
# turning invalid strings into `NaN`.

import pandas as pd

df = pd.DataFrame({
    "Price": ["100", "200", "300$", "400", "five hundred", "600"]
})

print(df)

          Price
0           100
1           200
2          300$
3           400
4  five hundred
5           600

In [36]:
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

print(df)

   Price
0  100.0
1  200.0
2    NaN
3  400.0
4    NaN
5  600.0

In [37]:
# ### Q60. Remove special characters from text data.
# > 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)`
# — use regex to keep only alphanumeric characters.

import pandas as pd

df = pd.DataFrame({
    "Text": ["Hello!!!", "Good@Morning", "Pandas#Data$Science", "Clean-this_text"]
})

print(df)

                  Text
0             Hello!!!
1         Good@Morning
2  Pandas#Data$Science
3      Clean-this_text

In [ ]:
 # [^...] - remove everything except these
#  [^a-zA-Z0-9 ]
df["Text"] = df["Text"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True) 

print(df)

                Text
0              Hello
1        GoodMorning
2  PandasDataScience
3      Cleanthistext

In [2]:
# ### Q61. Filter rows using AND condition.
# > 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]`
# — wrap each condition in parentheses and use `&`.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice", "Bob"],
    "Age": [25, 30, 22, 35],
    "City": ["Mumbai", "Delhi", "Mumbai", "Delhi"]
})

print(df)

    Name  Age    City
0   John   25  Mumbai
1   Mary   30   Delhi
2  Alice   22  Mumbai
3    Bob   35   Delhi

In [40]:
result = df[(df["Age"] > 25) & (df["City"] == "Delhi")]

print(result)

   Name  Age   City
1  Mary   30  Delhi
3   Bob   35  Delhi

In [41]:
df[
    (df["Age"] > 20) &
    (df["Age"] < 35) &
    (df["City"] == "Mumbai")
]

    Name  Age    City
0   John   25  Mumbai
2  Alice   22  Mumbai

In [42]:
# ### Q62. Filter rows using OR condition.
# > 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]`
# — use `|` between conditions.

result = df[(df["Age"] > 25) | (df["City"] == "Delhi")]

print(result)

   Name  Age   City
1  Mary   30  Delhi
3   Bob   35  Delhi

In [43]:
# ### Q63. Filter rows using NOT condition.
# > 💡 **Hint:** `df[~(df["col"] == "val")]` 
# — use `~` to negate a boolean condition.

result = df[~(df["City"] == "Mumbai")]

print(result)

   Name  Age   City
1  Mary   30  Delhi
3   Bob   35  Delhi

In [ ]:
# ### Q64. Sort DataFrame by column values.
# > 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, 
# `by=["col1","col2"]` for multi-column sort.

# 1. Sort by a single column Ascending order (default)

df.sort_values("Age")

    Name  Age    City
2  Alice   22  Mumbai
0   John   25  Mumbai
1   Mary   30   Delhi
3    Bob   35   Delhi

In [45]:
#  Sort in descending order
df.sort_values("Age", ascending=False)

    Name  Age    City
3    Bob   35   Delhi
1   Mary   30   Delhi
0   John   25  Mumbai
2  Alice   22  Mumbai

In [ ]:
# ### Q65. Sort DataFrame by index.
# > 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

# Sort columns (axis=1) - sort column names alphabetically
df.sort_index(axis=1)

   Age    City   Name
0   25  Mumbai   John
1   30   Delhi   Mary
2   22  Mumbai  Alice
3   35   Delhi    Bob

In [49]:
# Sort by index (rows)
df.sort_index()

    Name  Age    City
0   John   25  Mumbai
1   Mary   30   Delhi
2  Alice   22  Mumbai
3    Bob   35   Delhi

In [47]:
# Sort index in descending order
df.sort_index(ascending=False)

    Name  Age    City
3    Bob   35   Delhi
2  Alice   22  Mumbai
1   Mary   30   Delhi
0   John   25  Mumbai

In [51]:
# ### Q66. Add calculated column.
# > 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or
# use `.assign(new=lambda x: ...)` for chainable operations.

import pandas as pd

df = pd.DataFrame({
    "Price": [100, 200, 300],
    "Quantity": [2, 3, 4]
})

print(df)

   Price  Quantity
0    100         2
1    200         3
2    300         4

In [52]:
df["Total"] = df["Price"] * df["Quantity"]

print(df)

   Price  Quantity  Total
0    100         2    200
1    200         3    600
2    300         4   1200

In [55]:
df = df.assign(Total=lambda x: x["Price"] * x["Quantity"])

print(df)

   Price  Quantity  Total
0    100         2    200
1    200         3    600
2    300         4   1200

In [20]:
# ### Q67. Remove column using `drop()`.
# > 💡 **Hint:** `df.drop(columns=["col1","col2"])`.
# Always use the `columns=` parameter to be explicit.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice"],
    "Age": [25, 30, 28],
    "Salary": [50000, 60000, 55000]
})

print(df)

    Name  Age  Salary
0   John   25   50000
1   Mary   30   60000
2  Alice   28   55000

In [9]:
# Remove one column
df = df.drop(columns=["Salary"])

print(df)

    Name  Age
0   John   25
1   Mary   30
2  Alice   28

In [13]:
# Remove multiple columns
df = df.drop(columns=["Age", "Salary"])

print(df)

    Name
0   John
1   Mary
2  Alice

In [25]:
# ### Q68. Remove rows using `drop()`.
# > 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice", "Bob"],
    "Age": [25, 30, 28, 35]
})

print(df)

    Name  Age
0   John   25
1   Mary   30
2  Alice   28
3    Bob   35

In [26]:
# Remove rows with index labels 0 and 3
df = df.drop(index=[0, 3])
print(df)

    Name  Age
1   Mary   30
2  Alice   28

In [ ]:
# ### Q69. Use `map()` on a column.
# > 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict.
# Pass a function for element-wise transformation.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Grade": ["A", "B", "A", "C"]
})

df["Score"] = df["Grade"].map({
                                "A": 90,
                                "B": 80,
                                "C": 70
                            })

print(df)

  Grade  Score
0     A     90
1     B     80
2     A     90
3     C     70

In [34]:
df = pd.DataFrame({
    "Age": [20, 25, 30, 22]
})

df["Age_Double"] = df["Age"].map(lambda x: x * 2)

print(df)

   Age  Age_Double
0   20          40
1   25          50
2   30          60
3   22          44

In [ ]:
# ### Q70. Apply function using `apply()`.
# > 💡 **Hint:** `df["col"].apply(func)` for a Series.
# `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

In [ ]:
# Apply a function to a Series (column)

df["Age_Plus_5"] = df["Age"].apply(lambda x: x + 5)

print(df)

   Age  Age_Double  Age_Plus_5
0   20          40          25
1   25          50          30
2   30          60          35
3   22          44          27

In [36]:
#  Apply column-wise (axis=0)
# axis=0 means the function receives one column at a time.

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6]
})

print(df.apply(sum, axis=0))

A     6
B    15
dtype: int64

In [38]:
#  Apply row-wise (axis=1)

# axis=1 means the function receives one row at a time.

df["Row_Sum"] = df.apply(lambda row: row["A"] + row["B"], axis=1)

print(df)

   A  B  Row_Sum
0  1  4        5
1  2  5        7
2  3  6        9

In [ ]:

# ### Q71. Apply element-wise using `applymap()` / `map()`.
# > 💡 **Hint:** In older pandas use `df.applymap(func)`. 
# In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

In [39]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6]
})

result = df.applymap(lambda x: x * 10)

print(result)

    A   B
0  10  40
1  20  50
2  30  60

C:\Users\asus\AppData\Local\Temp\ipykernel_25496\2336707687.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  result = df.applymap(lambda x: x * 10)

In [40]:
result = df.map(lambda x: x * 10)

print(result)

    A   B
0  10  40
1  20  50
2  30  60

In [ ]:
# ### Q72. Chain multiple operations.
# > 💡 **Hint:** Use method chaining with 
# `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))`
# — wrap in parentheses for multi-line readability.

In [41]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice", "Bob"],
    "Age": [25, 30, 22, 35],
    "Score": [80, 90, 85, 70]
})

print(df)

    Name  Age  Score
0   John   25     80
1   Mary   30     90
2  Alice   22     85
3    Bob   35     70

In [42]:
result = (
    df.copy()
      .loc[df["Age"] > 25]
      .sort_values("Score", ascending=False)
      [["Name", "Age", "Score"]]
      .assign(Status=lambda x: x["Score"].apply(lambda s: "Pass" if s >= 80 else "Fail"))
      .reset_index(drop=True)
)

print(result)

   Name  Age  Score Status
0  Mary   30     90   Pass
1   Bob   35     70   Fail

In [ ]:
# # Q73. Normalize numeric columns (Min-Max).
# **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())`
# — result is in range [0, 1].

In [43]:
import pandas as pd

df = pd.DataFrame({
    "Marks": [10, 20, 30, 40, 50]
})

df["Marks_Normalized"] = (
    (df["Marks"] - df["Marks"].min()) /
    (df["Marks"].max() - df["Marks"].min())
)

print(df)

   Marks  Marks_Normalized
0     10              0.00
1     20              0.25
2     30              0.50
3     40              0.75
4     50              1.00

In [44]:

# ### Q74. Scale numerical data (Z-score standardization).
# > 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()`
# — result has mean=0 and std=1.

df["Marks_Z"] = (
    (df["Marks"] - df["Marks"].mean()) /
    df["Marks"].std()
)

print(df)

   Marks  Marks_Normalized   Marks_Z
0     10              0.00 -1.264911
1     20              0.25 -0.632456
2     30              0.50  0.000000
3     40              0.75  0.632456
4     50              1.00  1.264911

In [45]:
# ### Q75. Rank values in a column.
# > 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank,
# `method="dense"` to avoid gaps.

df["Rank"] = df["Marks"].rank(method="dense", ascending=False)

print(df)

   Marks  Marks_Normalized   Marks_Z  Rank
0     10              0.00 -1.264911   5.0
1     20              0.25 -0.632456   4.0
2     30              0.50  0.000000   3.0
3     40              0.75  0.632456   2.0
4     50              1.00  1.264911   1.0

In [49]:
import pandas as pd

df = pd.DataFrame({
    "Marks": [100, 90, 90, 80, 70]
})

df["Rank_dense"] = df["Marks"].rank(ascending=False, method="dense")

print(df)

   Marks  Rank_dense
0    100         1.0
1     90         2.0
2     90         2.0
3     80         3.0
4     70         4.0

In [ ]:
# ### Q76. Create bins using `cut()`.
# **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or
# pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

# pd.cut() is used to convert continuous numeric data into categories (bins).

In [50]:
import pandas as pd

df = pd.DataFrame({
    "Marks": [12, 25, 37, 45, 60, 72, 88, 95]
})

df["Category"] = pd.cut(df["Marks"], bins=4)

print(df)

   Marks         Category
0     12  (11.917, 32.75]
1     25  (11.917, 32.75]
2     37    (32.75, 53.5]
3     45    (32.75, 53.5]
4     60    (53.5, 74.25]
5     72    (53.5, 74.25]
6     88    (74.25, 95.0]
7     95    (74.25, 95.0]

In [52]:
df["Category"] = pd.cut(df["Marks"],
                        
    bins=[0, 25, 50, 75, 100],
    labels=["Low", "Mid", "High", "Top"]
)

print(df)

   Marks Category
0     12      Low
1     25      Low
2     37      Mid
3     45      Mid
4     60     High
5     72     High
6     88      Top
7     95      Top

In [ ]:
# ### Q77. Create bins using `qcut()`.
# > 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins.
# Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

In [53]:
import pandas as pd

df = pd.DataFrame({
    "Marks": [10, 20, 30, 40, 50, 60, 70, 80]
})

df["Quartile"] = pd.qcut(df["Marks"], q=4)

print(df)

   Marks       Quartile
0     10  (9.999, 27.5]
1     20  (9.999, 27.5]
2     30   (27.5, 45.0]
3     40   (27.5, 45.0]
4     50   (45.0, 62.5]
5     60   (45.0, 62.5]
6     70   (62.5, 80.0]
7     80   (62.5, 80.0]

In [54]:
df["Quartile"] = pd.qcut(
    df["Marks"],
    q=4,
    labels=["Q1", "Q2", "Q3", "Q4"]
)

print(df)

   Marks Quartile
0     10       Q1
1     20       Q1
2     30       Q2
3     40       Q2
4     50       Q3
5     60       Q3
6     70       Q4
7     80       Q4

In [55]:
# ### Q78. Count unique values.
# > 💡 **Hint:** `df["col"].nunique()` for the count, 
# `df["col"].value_counts()` for frequency per unique value.  

import pandas as pd

df = pd.DataFrame({
    "City": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi", "Surat"]
})

print(df["City"].nunique())

4

In [56]:
print(df["City"].value_counts())

City
Mumbai    2
Delhi     2
Pune      1
Surat     1
Name: count, dtype: int64

In [ ]:
# ### Q79. Replace multiple values at once.
# > 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or 
# use a list: `df.replace(["old1","old2"], "new")`.

In [57]:
import pandas as pd

df = pd.DataFrame({
    "Grade": ["A", "B", "C", "A", "B"]
})

df["Grade"] = df["Grade"].replace({
    "A": "Excellent",
    "B": "Good",
    "C": "Average"
})

print(df)

       Grade
0  Excellent
1       Good
2    Average
3  Excellent
4       Good

In [58]:
df["Grade"] = df["Grade"].replace(["A", "B"], "Pass")

print(df)

       Grade
0  Excellent
1       Good
2    Average
3  Excellent
4       Good

In [ ]:
# ### Q80. Create flag column based on condition.
# > 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)`
# — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

In [59]:
#  Using boolean condition + astype(int) (most common)
import pandas as pd

df = pd.DataFrame({
    "Marks": [35, 60, 45, 80, 25]
})

df["Pass_Flag"] = (df["Marks"] >= 40).astype(int)

print(df)

   Marks  Pass_Flag
0     35          0
1     60          1
2     45          1
3     80          1
4     25          0

In [60]:
#  Using np.where() (very popular in interviews)
import numpy as np

df["Pass_Flag"] = np.where(df["Marks"] >= 40, 1, 0)

print(df)

   Marks  Pass_Flag
0     35          0
1     60          1
2     45          1
3     80          1
4     25          0

In [ ]:
# ### Q81. Iterate over rows using `iterrows()`.
# > 💡 **Hint:** `for idx, row in df.iterrows():`
# — `idx` is the index label, `row` is a Series with column values.

In [61]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice"],
    "Marks": [85, 90, 78]
})

for idx, row in df.iterrows():
    print(idx, row["Name"], row["Marks"])

0 John 85
1 Mary 90
2 Alice 78

In [ ]:
# ### Q82. Iterate using `itertuples()`.
# > 💡 **Hint:** `for row in df.itertuples():` 
# — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Mary", "Alice"],
    "Marks": [85, 90, 78]
})

for row in df.itertuples():
    print(row)

In [64]:
# Access values using dot notation
for row in df.itertuples():
    print(row.Name, row.Marks)

John 85
Mary 90
Alice 78

In [65]:
# ### Q83. Iterate over columns.
# > 💡 **Hint:** `for col in df.columns:` then access `df[col]`.
# Or use `df.items()` which yields `(col_name, Series)` pairs.

for col in df.columns:
    print(col)

Name
Marks

In [67]:
# Using df.items()
for col_name, series in df.items():
    print(col_name)
    print(series)

Name
0     John
1     Mary
2    Alice
Name: Name, dtype: object
Marks
0    85
1    90
2    78
Name: Marks, dtype: int64

In [ ]:
# ### Q84. Avoid iteration using vectorization.
# > 💡 **Hint:** Replace `for` loops with direct column operations:
#     `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

df["New"] = df["Marks"] * 2 + 1

print(df)

    Name  Marks  New
0   John     85  171
1   Mary     90  181
2  Alice     78  157

In [70]:
# ### Q85. Group data using `groupby()`.
# > 💡 **Hint:** `df.groupby("col")["value_col"].mean()`
# — specify the grouping key and the aggregation in one line.

import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR", "Sales"],
    "Marks": [80, 90, 70, 85, 95]
})

result = df.groupby("Department")["Marks"].mean()

print(result)

Department
HR       87.5
IT       75.0
Sales    95.0
Name: Marks, dtype: float64

In [ ]:
# 2. Multiple aggregations on the same column
df.groupby("Department")["Marks"].agg(["mean", "min", "max", "count"])

            mean  min  max  count
Department
HR          87.5   85   90      2
IT          75.0   70   80      2
Sales       95.0   95   95      1

In [74]:
# ### Q86. Calculate sum per group.
# > 💡 **Hint:** `df.groupby("col")["value"].sum()` — 
# replace `sum` with any aggregation function.

result = df.groupby("Department")["Marks"].sum()

print(result)

Department
HR       175
IT       150
Sales     95
Name: Marks, dtype: int64

In [80]:
# ### Q87. Calculate multiple aggregations.
# > 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})`
# or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR", "Sales"],
    "Salary": [50000, 60000, 55000, 65000, 70000],
    "Bonus": [5000, 6000, 5500, 6500, 7000]
})

print(df)

  Department  Salary  Bonus
0         IT   50000   5000
1         HR   60000   6000
2         IT   55000   5500
3         HR   65000   6500
4      Sales   70000   7000

In [76]:
# Different aggregation for different columns
result = df.groupby("Department").agg({
    "Salary": "mean",
    "Bonus": "sum"
})

print(result)

             Salary  Bonus
Department
HR          62500.0  12500
IT          52500.0  10500
Sales       70000.0   7000

In [77]:
#  Named Aggregations 
result = df.groupby("Department").agg(
    Avg_Salary=("Salary", "mean"),
    Total_Bonus=("Bonus", "sum"),
    Max_Salary=("Salary", "max")
)

print(result)

            Avg_Salary  Total_Bonus  Max_Salary
Department
HR             62500.0        12500       65000
IT             52500.0        10500       55000
Sales          70000.0         7000       70000

In [78]:
# ### Q88. Group by multiple columns.
# > 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()`
# — pass a list of column names.

import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "IT"],
    "Gender": ["M", "F", "M", "F", "M"],
    "Salary": [50000, 60000, 55000, 65000, 70000]
})

print(df)

  Department Gender  Salary
0         IT      M   50000
1         IT      F   60000
2         HR      M   55000
3         HR      F   65000
4         IT      M   70000

In [79]:
result = df.groupby(["Department", "Gender"])["Salary"].mean()

print(result)

Department  Gender
HR          F         65000.0
            M         55000.0
IT          F         60000.0
            M         60000.0
Name: Salary, dtype: float64

In [ ]:
# Multiple aggregations
result = df.groupby(["Department", "Gender"]).agg(
    Avg_Salary=("Salary", "mean"),
    Max_Salary=("Salary", "max"),
    Count=("Salary", "count")
)

print(result)

In [82]:
# ### Q89. Filter grouped data.
# > 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)`
# — keeps entire groups satisfying the condition.

result = df.groupby("Department").filter(
    lambda g: g["Salary"].mean() > 60000
)

print(result)

  Department  Salary  Bonus
1         HR   60000   6000
3         HR   65000   6500
4      Sales   70000   7000

In [83]:
# ### Q90. Transform grouped data using `transform()`.
# > 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` 
# — returns a Series **same size as the original DataFrame** filled with group statistics.

df["Dept_Avg_Salary"] = (df.groupby("Department")["Salary"].transform("mean"))

print(df)

  Department  Salary  Bonus  Dept_Avg_Salary
0         IT   50000   5000          52500.0
1         HR   60000   6000          62500.0
2         IT   55000   5500          52500.0
3         HR   65000   6500          62500.0
4      Sales   70000   7000          70000.0

In [85]:

# ### Q91. Apply custom function in groupby.
# > 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())`
# — pass any function that takes a Series and returns a scalar.

# Custom function: Range (Max - Min)
result = df.groupby("Department")["Salary"].agg(lambda s: s.max() - s.min())

print(result)

Department
HR       5000
IT       5000
Sales       0
Name: Salary, dtype: int64

In [86]:
def salary_range(s):
    return s.max() - s.min()

result = df.groupby("Department")["Salary"].agg(salary_range)

print(result)

Department
HR       5000
IT       5000
Sales       0
Name: Salary, dtype: int64

In [87]:
# ### Q92. Create basic pivot table.
# pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.

import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Sales"],
    "Gender": ["M", "F", "M", "F", "M"],
    "Salary": [50000, 60000, 55000, 65000, 70000]
})

print(df)

  Department Gender  Salary
0         IT      M   50000
1         IT      F   60000
2         HR      M   55000
3         HR      F   65000
4      Sales      M   70000

In [88]:
result = pd.pivot_table(df,values="Salary",index="Department",columns="Gender",aggfunc="mean")

print(result)

Gender            F        M
Department
HR          65000.0  55000.0
IT          60000.0  50000.0
Sales           NaN  70000.0

In [89]:
# ### Q93. Use multiple aggregation functions in pivot.
# > 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` 
# — the result will have a MultiLevel column header.

result = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc=["mean", "max"]
)

print(result)

               mean               max
Gender            F        M        F        M
Department
HR          65000.0  55000.0  65000.0  55000.0
IT          60000.0  50000.0  60000.0  50000.0
Sales           NaN  70000.0      NaN  70000.0

In [90]:
# ### Q94. Handle missing values in pivot tables.
# **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "IT", "HR"],
    "Gender": ["M", "F", "M"],
    "Salary": [50000, 60000, 55000]
})

print(df)

  Department Gender  Salary
0         IT      M   50000
1         IT      F   60000
2         HR      M   55000

In [91]:
# Pivot Table without handling missing values
result = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)

print(result)

Gender            F        M
Department
HR              NaN  55000.0
IT          60000.0  50000.0

In [ ]:
# Handling missing values using fill_value
result = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean",
    fill_value=0
)

print(result)

In [92]:
# ### Q95. Add margins (totals) in pivot tables.
# > 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

result = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="sum",
    margins=True,
    margins_name="TOTAL"
)

print(result)

Gender            F         M   TOTAL
Department
HR              NaN   55000.0   55000
IT          60000.0   50000.0  110000
TOTAL       60000.0  105000.0  165000

In [95]:
# ### Q96. Create multi-level pivot table.
# > 💡 **Hint:** Pass lists to `index` and `columns` parameters:
#     `index=["col1","col2"], columns=["col3"]`.

result = pd.pivot_table(
    df,
    values="Salary",
    index=["Department", "Gender"],
    columns="Gender",
    aggfunc="mean"
)

print(result)

Gender                   F        M
Department Gender
HR         M           NaN  55000.0
IT         F       60000.0      NaN
           M           NaN  50000.0

In [96]:
# ### Q97. Convert DataFrame to pivot format.
# > 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` 
# — requires **unique** combinations of row/column keys (no aggregation).

import pandas as pd

df = pd.DataFrame({
    "Student": ["A", "A", "B", "B"],
    "Subject": ["Math", "Science", "Math", "Science"],
    "Marks": [80, 90, 70, 85]
})

print(df)

  Student  Subject  Marks
0       A     Math     80
1       A  Science     90
2       B     Math     70
3       B  Science     85

In [97]:
# Convert to pivot format

result = df.pivot(
    index="Student",
    columns="Subject",
    values="Marks"
)

print(result)

Subject  Math  Science
Student
A          80       90
B          70       85

In [108]:
# ### Q98. Compare pivot vs groupby.
# > 💡 **Hint:** `groupby()` is more flexible and returns a flat structure.
# `pivot_table()` gives a 2D grid and handles duplicates with aggregation. 
# `pivot()` does **no aggregation** and fails on duplicates.

import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "IT"],
    "Gender": ["M", "F", "M", "F", "M"],
    "City": ["Mumbai", "Mumbai", "Pune", "Pune", "Delhi"],
    "Salary": [50000, 60000, 55000, 65000, 70000]
})

print(df)

  Department Gender    City  Salary
0         IT      M  Mumbai   50000
1         IT      F  Mumbai   60000
2         HR      M    Pune   55000
3         HR      F    Pune   65000
4         IT      M   Delhi   70000

In [109]:
# groupby() (Flexible aggregation tool)
df.groupby("Department")["Salary"].mean()

Department
HR    60000.0
IT    60000.0
Name: Salary, dtype: float64

In [110]:
# pivot_table()
result = pd.pivot_table(
    df,
    values="Salary",
    index="Department",
    columns="Gender",
    aggfunc="mean",
   
)

print(result)

Gender            F        M
Department
HR          65000.0  55000.0
IT          60000.0  60000.0

In [ ]:
# ### Q99. Build summary report using pivot table.
# >**Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation.
# Export with `.to_csv()` or `.to_excel()`.

import pandas as pd

df = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "East"],
    "Product": ["A", "B", "A", "B", "A"],
    "Sales": [100, 150, 200, 250, 300]
})

print(df)

In [ ]:
#  Create summary pivot table
report = pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name="TOTAL"
)

print(report)

In [111]:
# Export to CSV
report.to_csv("summary_report.csv")

NameError: name 'report' is not defined

In [112]:
# Export to Excel
report.to_excel("summary_report.xlsx")

NameError: name 'report' is not defined

In [1]:
# ### Q100. Create an end-to-end analysis workflow.
# > 💡 **Hint:** Follow this pipeline:  
# > 1. Load data → 2. Inspect (shape, dtypes, nulls) →
# 3. Clean (fillna, drop_duplicates) → 4. Feature engineer →
# 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.

# 1. Load Data
import pandas as pd

df = pd.read_csv("data.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
# 2. Inspect Data

Check structure and quality:

df.head()
df.shape
df.info()
df.describe()
df.isnull().sum()

In [114]:
#3. Clean Data
#Handle missing values

df.fillna(0, inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

In [ ]:
# 4. Feature Engineering

# Create new meaningful columns:

df["Total"] = df["Price"] * df["Quantity"]
df["Discounted"] = df["Total"] * 0.9

In [ ]:
# 5. GroupBy / Pivot Analysis
# GroupBy example

summary = df.groupby("Category")["Total"].sum()

In [ ]:
import pandas as pd

# 1. LOAD DATA

df = pd.read_csv("data.csv")   # replace with your file

# ---------------------------
# 2. INSPECT DATA
# ---------------------------
print(df.head())
print(df.shape)
print(df.info())
print(df.isnull().sum())

# ---------------------------
# 3. CLEAN DATA
# ---------------------------

# Fill missing values (numeric example)
df.fillna(0, inplace=True)

# Remove duplicates
df.drop_duplicates(inplace=True)

# ---------------------------
# 4. FEATURE ENGINEERING
# ---------------------------

# Example: create new column
df["Total"] = df["Price"] * df["Quantity"]

df["Discounted_Total"] = df["Total"] * 0.9

# ---------------------------
# 5. GROUPBY ANALYSIS
# ---------------------------

category_summary = df.groupby("Category")["Total"].sum()

print(category_summary)

# ---------------------------
# 6. PIVOT TABLE ANALYSIS
# ---------------------------

pivot = pd.pivot_table(
    df,
    values="Total",
    index="Category",
    columns="Region",
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name="TOTAL"
)

print(pivot)

# ---------------------------
# 7. SORTING & RANKING
# ---------------------------

df_sorted = df.sort_values(by="Total", ascending=False)

df["Rank"] = df["Total"].rank(ascending=False)

# ---------------------------
# 8. FINAL INSIGHTS
# ---------------------------

top_categories = df.groupby("Category")["Total"].sum().sort_values(ascending=False)

print(top_categories)

# ---------------------------
# 9. EXPORT RESULTS
# ---------------------------

df.to_csv("cleaned_data.csv", index=False)
pivot.to_csv("summary_report.csv")

with pd.ExcelWriter("final_report.xlsx") as writer:
    df.to_excel(writer, sheet_name="Cleaned_Data", index=False)
    pivot.to_excel(writer, sheet_name="Pivot_Summary")

print("Analysis completed and files exported successfully.")